name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  http: ^1.2.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - termometer.jpg 
    - barometer.jpg 
    - humidity.jpg 
    - cloudy.jpg 
    - termometer.jpg
  # - barometer2.jpg
    - humidity.jpg
    - cloudy.jpg
    - baro.jpg